apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-data-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-data
  template:
    metadata:
      labels:
        app: books-data
    spec:
      containers:
      - name: books-data-container
        image: whosumit/books_data
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: books-data-service
  labels:
    app: books-data
spec:
  selector:
    app: books-data
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer