apiVersion: v1
kind: Service
metadata:
  name: books-data-service
  labels:
    app: books-data
spec:
  selector:
    app: books-data
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    externalIPs:
  type: LoadBalancer